### ISSUE TITLE
HTML Optimization

### ISSUE THREAD

**Issue by Hugoto69** [IchiiDev/profile#5]
# HTML Optimization
### Element div is not allowed here
```html
<title id="vue-managed">{{ username }}</title>
```

**Comment by IchiiDev** [comment]
Hi, thank you for bringing these issues to my attention.
Can you please be more descriptive concerning the following ? 
`Element div is not allowed here`
If I understand correctly, you wouldn't recommend giving an ID to the title element ?

**Comment by IchiiDev** [comment]
Never mind, your issue was missing the parent element, I see what you're saying. Although I will try to improve this implementation, I couldn't get to make Vue work directly inside a `<head>` parent.

**Comment by IchiiDev** [comment]
There fixed ! :)
Next time perhaps, please consider opening a Pull Request instead of multiple issues if you already suggest a fix in the latter.
